/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VHead {
        "icon": string;
        "name": string;
        "site": string;
    }
}
declare global {
    interface HTMLVHeadElement extends Components.VHead, HTMLStencilElement {
    }
    var HTMLVHeadElement: {
        prototype: HTMLVHeadElement;
        new (): HTMLVHeadElement;
    };
    interface HTMLElementTagNameMap {
        "v-head": HTMLVHeadElement;
    }
}
declare namespace LocalJSX {
    interface VHead {
        "icon"?: string;
        "name"?: string;
        "site"?: string;
    }
    interface IntrinsicElements {
        "v-head": VHead;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "v-head": LocalJSX.VHead & JSXBase.HTMLAttributes<HTMLVHeadElement>;
        }
    }
}
