/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VFooter {
        "brand": string;
    }
    interface VHeader {
        "brand": string;
        "navstyle": boolean;
    }
    interface VSubHeader {
        "brand": string;
        "shadow": boolean;
        "theme": string;
    }
}
declare global {
    interface HTMLVFooterElement extends Components.VFooter, HTMLStencilElement {
    }
    var HTMLVFooterElement: {
        prototype: HTMLVFooterElement;
        new (): HTMLVFooterElement;
    };
    interface HTMLVHeaderElement extends Components.VHeader, HTMLStencilElement {
    }
    var HTMLVHeaderElement: {
        prototype: HTMLVHeaderElement;
        new (): HTMLVHeaderElement;
    };
    interface HTMLVSubHeaderElement extends Components.VSubHeader, HTMLStencilElement {
    }
    var HTMLVSubHeaderElement: {
        prototype: HTMLVSubHeaderElement;
        new (): HTMLVSubHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "v-footer": HTMLVFooterElement;
        "v-header": HTMLVHeaderElement;
        "v-sub-header": HTMLVSubHeaderElement;
    }
}
declare namespace LocalJSX {
    interface VFooter {
        "brand"?: string;
    }
    interface VHeader {
        "brand"?: string;
        "navstyle"?: boolean;
    }
    interface VSubHeader {
        "brand"?: string;
        "shadow"?: boolean;
        "theme"?: string;
    }
    interface IntrinsicElements {
        "v-footer": VFooter;
        "v-header": VHeader;
        "v-sub-header": VSubHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "v-footer": LocalJSX.VFooter & JSXBase.HTMLAttributes<HTMLVFooterElement>;
            "v-header": LocalJSX.VHeader & JSXBase.HTMLAttributes<HTMLVHeaderElement>;
            "v-sub-header": LocalJSX.VSubHeader & JSXBase.HTMLAttributes<HTMLVSubHeaderElement>;
        }
    }
}
